### PR TITLE
fix reset: clear state of resolution, heater and error

### PR DESCRIPTION
**Pull request by jnsbyr**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks for the PR, will look into it later this week.

**Comment by RobTillaart** [comment]
Looks like a bug indeed.

**Comment by RobTillaart** [comment]
@jnsbyr 
Thanks for the PR
- Merged into master
- created release 0.4.1
- published on PlatformIO
- synced with my local branch

Can you merge latest version into your other PR? 
Thanks again!

**Comment by jnsbyr** [comment]
> Can you merge latest version into your other PR?

Will do. 👍

**Pull request merged**
